name: firebase_test
description: "Project for testing firebase_fetures"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^17.1.2
  go_router: ^14.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
